[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/elasticsearch/*"
  to = "https://my-elasticsearch-project-f3e988.es.us-central1.gcp.elastic.cloud:443/:splat"
  status = 200
  force = true
  headers = {Authorization = "ApiKey T1B1OHpKY0JGTzVJOXhyWUYtUW86clpsb3ZJVzV0Q0dOSlBFdTFUQ3RKdw=="}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200