[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/elasticsearch/*"
  to = "https://localhost:9200/:splat"
  status = 200
  force = true
  headers = {Authorization = ""}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200